#pragma once


namespace Client
{
	enum class LEVEL				{ STATIC, LOADING, LOGO, HANGER, PRACTICE, GAMEPLAY, MAPTOOL, PARTICLETOOL, END };
	enum class GEAR					{ DRIVE, REVERSE, END };
	enum class PART_REPAINT			{ BODY, TURRET, GUN, END };
	enum class CONSUMABLES			{ HAND_EXTINGUISHER, SMALL_REPAIR_KIT, SMALL_MED_KIT, END };
	enum class COLLISION_GROUP		{ BODY, TURRET, SHELL, MODULE, TREE, BUILDING, WALL, DAMAGE_COLL, END };
}


