#pragma once


namespace Client
{
	enum class LEVEL				{ STATIC, LOADING, LOGO, HANGER, PRACTICE, GAMEPLAY, MAPTOOL, END };
	enum class GEAR					{ DRIVE, REVERSE, END };
	enum class MODULE				{ ENGINE, TRACK_LEFT, TRACK_RIGHT, TURRET, GUN, SURVEYING_DEVICE, RADIO, FUEL_TANK, AMMO_BAY, END };
	enum class MODULE_STATE			{ DESTROYED, DAMAGED, FUNCTIONAL, END };
	enum class PART_REPAINT			{ BODY, TURRET, GUN, END };
}


